core/urls.py
from django.urls import path

from .views import dashboard

app_name = "core"

urlpatterns = [
    path("", dashboard, name="dashboard"),
]

django_project/urls.py
import notifications.urls
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", include("core.urls")),
    path("users/", include("users.urls")),
    path("journal/", include("journal.urls")),
    path("documents/", include("documents.urls")),
    path("adminpanel/", admin.site.urls),
    path(
        "accounts/", include("django.contrib.auth.urls")
    ),  # Must be "accounts/" to work properly
    # 3rd
    path(
        "inbox/notifications/", include(notifications.urls, namespace="notifications")
    ),
    path("__debug__/", include("debug_toolbar.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# Configure Admin panel titles
admin.site.site_header = "Панель управления Журнала Дежурства"
admin.site.site_title = "Панель управления Журнала Дежурства"
admin.site.index_title = "Управление Журналом Дежурства"

documents/urls.py
from django.urls import path

from .views import DocumentDetailView, DocumentListView, document_acquaint

app_name = "documents"

urlpatterns = [
    path("", DocumentListView.as_view(), name="document_list"),
    path("document/<int:pk>/", DocumentDetailView.as_view(), name="document_detail"),
    path(
        "document/acquaint/<int:pk>/", document_acquaint, name="document_acquaint"
    ),  # HTMX view
]

journal/urls.py
from django.urls import path

from .api import (
    CommentListAPI,
    TaskCategoryListAPI,
    TaskDetailAPI,
    TaskListAPI,
    TaskListStatsAPI,
    comment_create_api,
    comment_edit_api,
    task_acquaint_api,
    task_toggle_favorite_api,
)
from .views import (
    CompletedTaskListView,
    FavoriteTaskListView,
    PrivateTaskListView,
    ReportListView,
    SearchView,
    TableTaskListView,
    TableTaskListVueView,
    TaskCreateView,
    TaskDetailView,
    TaskListView,
    TaskUpdateView,
    comment_add,
    comment_archive,
    comment_delete,
    comment_edit,
    comment_edit_save,
    comment_show,
    task_acquaint,
    task_search,
    task_toggle_favorite,
)

app_name = "journal"

urlpatterns = [
    path("tasks/", TaskListView.as_view(), name="task_list"),
    path("tasks/private/", PrivateTaskListView.as_view(), name="private_task_list"),
    path("tasks/favorites/", FavoriteTaskListView.as_view(), name="favorite_task_list"),
    path(
        "tasks/completed/", CompletedTaskListView.as_view(), name="completed_task_list"
    ),
    path("tasks/table/", TableTaskListView.as_view(), name="task_list_table"),
    path(
        "tasks/table/vue/", TableTaskListVueView.as_view(), name="task_list_table_vue"
    ),
    path("task/<int:pk>/", TaskDetailView.as_view(), name="task_detail"),
    path("task/create/", TaskCreateView.as_view(), name="task_create"),
    path("task/update/<int:pk>/", TaskUpdateView.as_view(), name="task_update"),
    path("task/<int:pk>/add_comment/", comment_add, name="task_comment_add"),
    path(
        "task/<int:task_pk>/delete_comment/<int:comment_pk>/",
        comment_delete,
        name="task_comment_delete",
    ),
    path(
        "task/<int:task_pk>/archive_comment/<int:comment_pk>/",
        comment_archive,
        name="task_comment_archive",
    ),
    path("task/comment/<int:comment_pk>/edit/", comment_edit, name="task_comment_edit"),
    path("task/comment/<int:comment_pk>/show/", comment_show, name="task_comment_show"),
    path(
        "task/comment/<int:comment_pk>/edit/save/",
        comment_edit_save,
        name="task_comment_edit_save",
    ),
    path("task/<int:pk>/acquaint/", task_acquaint, name="task_acquaint"),
    path("task/<int:pk>/favorite/", task_toggle_favorite, name="task_toggle_favorite"),
    path("tasks/search/", SearchView.as_view(), name="task_search"),
    path("reports/", ReportListView.as_view(), name="report_list"),
    path("tasks/htmx/search/", task_search, name="task_search_htmx"),
    # API views
    path("tasks/api/v1/stats/", TaskListStatsAPI.as_view(), name="api_task_stats"),
    path("tasks/api/v1/task_list/", TaskListAPI.as_view(), name="api_task_list"),
    path(
        "tasks/api/v1/task/<int:pk>/", TaskDetailAPI.as_view(), name="api_task_detail"
    ),
    path(
        "tasks/api/v1/task/<int:pk>/favorite/",
        task_toggle_favorite_api,
        name="api_task_toggle_favorite",
    ),
    path(
        "tasks/api/v1/category_list/",
        TaskCategoryListAPI.as_view(),
        name="api_task_category_list",
    ),
    path(
        "tasks/api/v1/comment_list/",
        CommentListAPI.as_view(),
        name="api_task_comment_list",
    ),
    path("tasks/api/v1/comment/", comment_create_api, name="api_task_comment_create"),
    path(
        "tasks/api/v1/comment/<int:pk>/edit/",
        comment_edit_api,
        name="api_task_comment_edit",
    ),
    path(
        "tasks/api/v1/task/<int:pk>/acquaint/",
        task_acquaint_api,
        name="api_task_acquaint",
    ),
]

templates/snippets/dashboard_timeline_items.html
{% load core_filters %}
{% load bleach_tags %}

{% for notify in notifications %}
  <!-- Each timeline item -->
  {# If there's next page, and it's the last item, add next page after it using HTMX #}
  {% if forloop.last and page_obj.has_next %}
    <div class="timeline__item"
         hx-get="{% url 'core:dashboard' %}?notifications_only=1&page={{ page_obj.next_page_number }}"
         hx-trigger="revealed" hx-swap="afterend">
  {% else %}
    <div class="timeline__item">
  {% endif %}
    <!-- The circle and title -->
    <div class="timeline__top mb-2">
      <!-- The circle -->
      <div class="timeline__circle text-center">
        {% if notify.verb_code == "favorites_add" %}
          <i class="fa-solid fa-star"></i>
        {% elif notify.verb_code == "task_add" %}
          <i class="fa-solid fa-list-check"></i>
        {% elif notify.verb_code == "task_edit" %}
          <i class="fa-solid fa-edit"></i>
        {% elif notify.verb_code == "task_completed" %}
          <i class="fa-solid fa-check"></i>
        {% elif notify.verb_code == "acquainted" %}
          <i class="fa-solid fa-file-signature"></i>
        {% elif notify.verb_code == "comment_add" %}
          <i class="fa-solid fa-comment"></i>
        {% elif notify.verb_code == "comment_edit" %}
          <i class="fa-solid fa-edit"></i>
        {% elif notify.verb_code == "report_add" %}
          <i class="fa-solid fa-table"></i>
        {% elif notify.verb_code == "user_logged_in" %}
          <i class="fa-solid fa-arrow-right-to-bracket"></i>
        {% elif notify.verb_code == "user_logged_out" %}
          <i class="fa-solid fa-arrow-right-from-bracket"></i>
        {% endif %}
      </div>

      <!-- The title -->
      <div class="timeline__title">
        {% include "snippets/user_avatar.html" with user=notify.actor size=24 %}
        {# Comment: #}
        {% if notify.verb_code == "comment_add" %}
          {{ notify.actor.short_name }}
          <a href="{{ notify.action_object.get_absolute_url }}">{{ notify.verb }}</a>
          к &laquo;<a href="{{ notify.target.get_absolute_url }}">{{ notify.target }}</a>&raquo;
        {% elif notify.verb_code == "report_add" %}
          {{ notify.verb }}
          &laquo;<a href="{{ notify.target.attachment.url }}">{{ notify.target }}</a>&raquo;
        {% elif notify.verb_code == "user_logged_in" or notify.verb_code == "user_logged_out" %}
          {{ notify.actor.short_name }}
          {{ notify.verb }}
        {% else %}
          {{ notify.actor.short_name }}
          {{ notify.verb }}
          &laquo;<a href="{{ notify.target.get_absolute_url }}">{{ notify.target|truncatechars:64 }}</a>&raquo;
        {% endif %}
        &middot; <span class="timeline__title__timestamp text-muted">{{ notify.timestamp }}</span>
      </div>
    </div>
    <!-- The description -->
    <div class="timeline__desc">
      {% if notify.verb_code == "comment_add" %}
      {# Comment #}
        <div class="card flex-grow-1">
          <div class="card-body">
            {{ notify.action_object.body|markdown|bleach|safe }}
          </div>
        </div>
      {% elif notify.verb_code == "task_edit" or notify.verb_code == "comment_edit" %}
      {# Task or comment updated (with history in accordion) #}
        <div class="accordion" id="accordionExample">
          <div class="accordion-item">
            <h2 class="accordion-header" id="headingTwo">
              <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapse-{{ notify.pk }}" aria-expanded="false" aria-controls="collapseTwo">
                Нажмите, чтобы увидеть что было изменено.
              </button>
            </h2>
            <div id="collapse-{{ notify.pk }}" class="accordion-collapse collapse" aria-labelledby="headingTwo" data-bs-parent="#accordionExample">
              <div class="accordion-body">
                {% if notify.previous_title %}
                  <p class="{% if notify.previous_body %}mb-3{% endif %}">
                    <b>Заголовок изменен на:</b> {{ notify.new_title }}
                    <br><br>
                    <span class="text-muted">Прежний заголовок: {{ notify.previous_title }}</span>
                  </p>
                {% endif %}
                {% if notify.previous_body %}
                  <p>
                    <b>Содержание изменено на:</b><br>
                    {{ notify.new_body|markdown|bleach|safe }}
                    <br>
                    <span class="text-muted">
                      Прежнее содержание:<br>
                      {{ notify.previous_body|markdown|bleach|safe }}
                    </span>
                  </p>
                {% endif %}
              </div>
            </div>
          </div>
        </div>
      {% endif %}
    </div>
  </div>
{% endfor %}

templates/snippets/document_detail_item.html
{% load core_filters %}
{% load bleach_tags %}

<div id="document">
  <div class="card {% if not user in document.users_acquainted.all %}card-new border-success{% endif %} mb-2">
    <div class="card-header text-muted">
      <div class="d-flex flex-wrap flex-md-nowrap align-items-center">
        <div class="flex-grow-1">
          <span data-bs-toggle="tooltip" data-bs-title="Дата и время создания документа" data-bs-delay='{"show":1000,"hide":0}'>
            <i class="fa-regular fa-calendar"></i> {{ document.created }}
          </span>
          <span data-bs-toggle="tooltip" data-bs-title="Автор документа" data-bs-delay='{"show":1000,"hide":0}'>
            &middot; <i class="fa-solid fa-user"></i> {{ document.author.short_name }}
          </span>
          {% if user.is_superuser %}
            &middot; <i class="fa-solid fa-eye"></i> {{ total_views }}
          {% endif %}
          &middot;  <i class="fa-solid fa-user-check"></i> {{ document.users_acquainted.count }}
          {% for user in document.users_acquainted.all %}
            {% include "snippets/user_avatar.html" with user=user size=24 %}
          {% endfor %}
        </div>
        <div class="btn-toolbar mb-2 mb-md-0">
          {% if user.is_superuser %}
            <!-- EDIT button only for superuser -->
            <a class="btn btn-sm btn-secondary ms-2" href="/adminpanel/documents/document/{{ document.pk }}/change/">
              <i class="fa-solid fa-pen-to-square"></i> В админке
            </a>
          {% endif %}
        </div>
      </div>
    </div>
    <div class="card-body document-card-body">
      {{ document.body|markdown|bleach|safe }}
      {% if document.attachment %}
        <p class="mt-3">
          <i class="fa-solid fa-paperclip"></i> Файл: <a href="{{ document.attachment.url }}">
            {{ document.attachment.name }}</a>
          ({{ document.attachment.size|filesizeformat }})
        </p>
      {% endif %}
    </div>
  </div>

  {% if document.is_completed %}
    <div class="alert alert-warning">
      <i class="fa-solid fa-file-circle-check"></i> Документ уже не актуален!
    </div>
  {% endif %}

  {% if not user in document.users_acquainted.all %}
    <div class="btn-toolbar mb-2 mb-md-0 justify-content-end">
      <button class="btn btn-sm btn-primary me-2"
              hx-post="{% url 'documents:document_acquaint' document.pk %}"
              hx-trigger="click"
              hx-target="#document"
              hx-swap="outerHTML">
        <i class="fa-solid fa-file-signature"></i> Ознакомлен
      </button>
    </div>
  {% endif %}
</div>

templates/snippets/document_list_item.html
<div class="card list-card {% if not user in document.users_acquainted.all %}card-new border-success{% else %}border-dark{% endif %} mb-2">
  <div class="card-header">
    {% if document.is_completed %}
      <i class="fa-solid fa-file-circle-check me-1"
          data-bs-toggle="tooltip" data-bs-title="Этот документ не актуален"
          data-bs-delay='{"show":1000,"hide":0}'>
      </i>
    {% endif %}
    <i class="fa-solid fa-tag"></i> <span class="text-muted">{{ document.category }}</span>
  </div>
  <div class="card-body">
    <h5 class="card-title mb-0">
      <a class="title-link" href="{{ document.get_absolute_url }}">
        {{ document.title }}
      </a>
    </h5>
    <!--
    <p class="card-text">
      {{ document.body|truncatechars:232 }}
    </p>
    -->
  </div>
  <div class="card-footer text-muted">
    <span data-bs-toggle="tooltip" data-bs-title="Дата и время создания документа" data-bs-delay='{"show":1000,"hide":0}'>
      <i class="fa-regular fa-calendar"></i> {{ document.created }}
    </span>
    <span data-bs-toggle="tooltip" data-bs-title="Ознакомленные пользователи" data-bs-delay='{"show":1000,"hide":0}'>
      &middot;  <i class="fa-solid fa-user-check"></i> {{ document.users_acquainted.count }}
      {% for user in document.users_acquainted.all %}
        {% include "snippets/user_avatar.html" with user=user size=24 %}
      {% endfor %}
    </span>
  </div>
</div>

templates/snippets/task_comment_edit.html
<div class="card-body" id="comment-body-{{ comment.pk }}">
  <form hx-post="{% url 'journal:task_comment_edit_save' comment.pk %}"
        hx-target="#comment-body-{{ comment.pk }}" hx-swap="outerHTML">
    <textarea class="form-control mb-1" name="updated_comment_text" rows="3">{{ comment.body  }}</textarea>
    <div class="btn-toolbar mb-md-0 justify-content-end">
      <button class="btn btn-secondary me-1"
              hx-get="{% url 'journal:task_comment_show' comment.pk %}"
              hx-target="#comment-body-{{ comment.pk }}"
              hx-swap="outerHTML">
        Отмена
      </button>
      <button class="btn btn-success">
        Сохранить
      </button>
    </div>
  </form>
</div>

templates/snippets/task_comment_show.html
{% load core_filters %}

<div class="card-body" id="comment-body-{{ comment.pk }}">
  {{ comment.body|markdown|safe }}
</div>

templates/snippets/task_comments_block.html
{% load core_filters %}
{% load journal_filters %}
{% load bleach_tags %}
{% load static %}

<div id="comments">
  <!-- Timeline demo -->
  <div class="timeline">
    <!-- Left vertical line -->
    <div class="timeline__line"></div>

    <!-- The timeline items timeline -->
    <div class="timeline__items">
      {% for comment in task.active_comments.all %}
        <!-- Each timeline item -->
        <div class="timeline__item mb-3">
          <!-- The circle and title -->
          <div class="timeline__top mb-2">
            <!-- The circle -->
            <div class="timeline__circle text-center">
              <i class="fa-solid fa-comment"></i>
            </div>

            <!-- The title -->
            <div class="timeline__title" id="comment-{{ comment.pk }}">
              Добавлен комментарий:
            </div>
          </div>
          <!-- The description which has round userpic -->
          <div class="timeline__desc_avatar">
            <div class="d-flex">
              <!-- Comment author's avatar -->
              <div class="timeline__desc_avatar__avatar mt-3 me-2">
                {% include "snippets/user_avatar.html" with user=comment.author size=48 %}
              </div>
              <!-- Comment card -->
              <div class="card flex-grow-1 {% if user in comment.users_acquainted.all %}bubble{% else %}card-new border-success bubble-new{% endif %}"
{#                   hx-confirm="Вы уверены, что хотите удалить этот комментарий?"#}
{#                   hx-target="#comments"#}
                   hx-swap="outerHTML">
                <div class="card-header d-flex text-muted">
                  <!-- Comment info -->
                  <div class="flex-grow-1">
                    <i class="fa-solid fa-user"></i> {{ comment.author.short_name }}, {{ comment.created }}
                  </div>
                  <!-- Buttons -->
                  <div>
                    {# ADMIN edit #}
                    {% if user.is_superuser %}
                      <a class="toolbar-link toolbar-link-primary" href="/adminpanel/journal/comment/{{ comment.pk }}/change/"
                         data-bs-toggle="tooltip" data-bs-title="Редактировать в панели администратора"
                         data-bs-delay='{"show":1000,"hide":0}'>
                        <i class="fa-solid fa-pencil"></i>
                      </a>
                    {% endif %}
                    <!-- EDIT and ARCHIVE (do not show to author if task is completed -->
                    {% if user.is_superuser or comment.author == user and not task.is_completed  %}
                      <a class="toolbar-link toolbar-link-primary"
                         hx-get="{% url 'journal:task_comment_edit' comment.pk %}"
                         hx-target="#comment-body-{{ comment.pk }}"
                         hx-swap="outerHTML"
                         data-bs-toggle="tooltip" data-bs-title="Редактировать комментарий"
                         data-bs-delay='{"show":1000,"hide":0}'>
                        <i class="fa-solid fa-pen-to-square"></i>
                      </a>
                      <a class="toolbar-link toolbar-link-danger"
                         hx-delete="{% url 'journal:task_comment_archive' task.pk comment.pk %}"
                         hx-confirm="Вы уверены, что хотите удалить этот комментарий?"
                         hx-target="#comments"
                         hx-swap="outerHTML"
                         data-bs-toggle="tooltip" data-bs-title="Удалить комментарий"
                         data-bs-delay='{"show":1000,"hide":0}'>
                        <i class="fa-solid fa-trash"></i>
                      </a>
                    {% endif %}
                    <!-- DELETE -->
                    {% if user.is_superuser %}
                      <a class="toolbar-link toolbar-link-danger"
                         hx-delete="{% url 'journal:task_comment_delete' task.pk comment.pk %}"
                         hx-confirm="Вы уверены, что хотите удалить этот комментарий?"
                         hx-target="#comments"
                         hx-swap="outerHTML"
                         data-bs-toggle="tooltip" data-bs-title="Удалить комментарий (администратор)"
                         data-bs-delay='{"show":1000,"hide":0}'>
                        <i class="fa-solid fa-trash-can-arrow-up"></i>
                      </a>
                    {% endif %}
                  </div>
                </div>
                <div class="card-body" id="comment-body-{{ comment.pk }}">
                  {{ comment.body|markdown|bleach|safe }}
                </div>
              </div>
            </div>
          </div>
        </div>
      {% endfor %}
    </div>
  </div>

  {% if task.is_completed %}
    <div class="alert alert-success">
      <i class="fa-solid fa-file-circle-check"></i> Задача завершена.
    </div>
    {% if not task|is_user_acquainted:user %}
      {# NB: Some code duplication here, gotta refactor eventually... #}
      <div class="btn-toolbar mb-2 mb-md-0 justify-content-end">
        <button class="btn btn-sm btn-primary me-2 mb-3"
                hx-post="{% url 'journal:task_acquaint' task.pk %}"
                hx-trigger="click"
                hx-target="#task_with_comments"
                hx-swap="outerHTML">
          <i class="fa-solid fa-file-signature"></i> Ознакомлен
        </button>
      </div>
    {% endif %}
  {% else %}
    <form class="comments-form-new" hx-post="{% url 'journal:task_comment_add' task.pk %}" hx-target="#comments" hx-swap="outerHTML">
      <div class="mb-3">
        <label for="comment_text" class="form-label">Добавить комментарий:</label>
        <div class="d-flex">
          <div class="me-2">
            {% include "snippets/user_avatar.html" with user=user size=48 %}
          </div>
          <div class="flex-grow-1">
            <textarea class="form-control" id="comment-text" name="comment_text" rows="3"></textarea>
          </div>
        </div>
      </div>

      <div class="d-flex mb-3 flex-wrap">
        <div class="flex-grow-1">
          <input class="form-check-input" type="checkbox" value="complete" id="check-complete-task"
                 name="check_complete_task" disabled>
          <label class="form-check-label" for="check-complete-task">
            Завершить задачу с этим комментарием
          </label>
        </div>
        <div class="btn-toolbar mb-2 mb-md-0 justify-content-end">
          {% if not task|is_user_acquainted:user %}
            <button class="btn btn-sm btn-primary me-2"
                    hx-post="{% url 'journal:task_acquaint' task.pk %}"
                    hx-trigger="click"
                    hx-target="#task_with_comments"
                    hx-swap="outerHTML">
              <i class="fa-solid fa-file-signature"></i> Ознакомлен
            </button>
          {% endif %}
          <!-- if checkbox checked, change button title to "comment and close": -->
          <button class="btn btn-sm btn-success" id="submit-button" type="submit">
            <i class="fa-solid fa-comment"></i> Комментировать
          </button>
        </div>
      </div>
    </form>
  {% endif %}
</div>

<script>
  // These three variables are declared in "task_detail.html" <script> section.
  // This separation is needed for HTMX to work properly on partial page reloads, when these DOM elements are changed.
  completedCheckBox = document.getElementById('check-complete-task');
  commentTextarea = document.getElementById('comment-text');
  submitButton = document.getElementById('submit-button');

  commentTextarea.addEventListener("keyup", (event) => {
    let commentText = commentTextarea.value.toString().trimStart().trimEnd();

    if(commentText.length >= 5) {
      completedCheckBox.disabled = false;
    } else {
      completedCheckBox.disabled = true;
      completedCheckBox.checked = false;
    }

    let eventChange = new Event('change');
    completedCheckBox.dispatchEvent(eventChange);
  });

  completedCheckBox.addEventListener("change", (event) => {
    if (event.currentTarget.checked) {
      submitButton.innerHTML = '<i class="fa-solid fa-file-circle-check"></i> Завершить задачу';
    } else {
      submitButton.innerHTML = '<i class="fa-solid fa-comment"></i> Комментировать';
    }
  });
</script>

templates/snippets/task_full_block.html
{% load core_filters %}
{% load bleach_tags %}

<div id="task_with_comments">
  <div class="card {% if not user in task.users_acquainted.all %}card-new border-success{% endif %} mb-2">
    <div class="card-header text-muted">
      <div class="d-flex flex-wrap flex-md-nowrap align-items-center">
        <div class="flex-grow-1">
          {% include "snippets/task_list_item_favorite_button.html" with task=task %}
          {% if task.is_private %}
            <i class="fa-solid fa-lock me-1" data-bs-toggle="tooltip" data-bs-title="Личная задача, доступна только вам" data-bs-delay='{"show":1000,"hide":0}'></i>
          {% endif %}
          <span data-bs-toggle="tooltip" data-bs-title="Дата и время создания задачи" data-bs-delay='{"show":1000,"hide":0}'>
            <i class="fa-regular fa-calendar"></i> {{ task.created }}
          </span>
          <span data-bs-toggle="tooltip" data-bs-title="Автор задачи" data-bs-delay='{"show":1000,"hide":0}'>
            &middot; <i class="fa-solid fa-user"></i> {{ task.author.short_name }}
          </span>
          <!-- &middot;  <i class="fa-solid fa-user-check"></i> {{ task.users_acquainted.count }} -->
          {% if task.due_date and not task.is_completed  %}
          &middot;
          <span class="{% if task.is_overdue and not task.is_completed %}due-date-overdue{% elif task.is_due_today and not task.is_completed %}due-date-today{% endif %}"
                data-bs-toggle="tooltip" data-bs-title="Установленный срок выполнения задачи" data-bs-delay='{"show":1000,"hide":0}'>
            <i class="fa-solid fa-calendar-day"></i> {{ task.due_date }}
          </span>
          {% endif %}
          {% if task.completed and task.is_completed %}
            <span data-bs-toggle="tooltip" data-bs-title="Дата и время завершения задачи" data-bs-delay='{"show":1000,"hide":0}'>
              &middot;
              <i class="fa-solid fa-calendar-check"></i>
              {{ task.completed }}
            </span>
          {% endif %}
          {% if user.is_superuser %}
            &middot; <i class="fa-solid fa-eye"></i> {{ total_views }}
          {% endif %}
        </div>
        <div class="btn-toolbar mb-2 mb-md-0">
          {% if user.is_superuser or not task.is_completed and task.author == user %}
            <!-- EDIT button only for superuser or author for open tasks -->
            <a class="btn btn-sm btn-secondary" href="{% url 'journal:task_update' task.pk %}">
              <i class="fa-solid fa-pen-to-square"></i> Изменить
            </a>
          {% endif %}
          {% if user.is_superuser %}
            <!-- EDIT button only for superuser or author for open tasks -->
            <a class="btn btn-sm btn-secondary ms-2" href="/adminpanel/journal/task/{{ task.pk }}/change/">
              <i class="fa-solid fa-pen-to-square"></i> В админке
            </a>
          {% endif %}
        </div>
      </div>
    </div>
    <div class="card-body task-card-body">
      {{ task.body|markdown|bleach|safe }}
      {% if task.attachment %}
        <p class="mt-3">
          <i class="fa-solid fa-paperclip"></i> Файл: <a href="{{ task.attachment.url }}">
            {{ task.attachment.name }}</a>
          ({{ task.attachment.size|filesizeformat }})
        </p>
      {% endif %}
    </div>
  </div>

  {% include 'snippets/task_comments_block.html' with task=task %}
</div>

templates/snippets/task_list_item_favorite_button.html
<button class="{% if task.is_favorite or is_favorite %}star-link-favorite{% else %}star-link{% endif %} me-0"
        hx-post="{% url 'journal:task_toggle_favorite' task.pk %}"
        hx-target="this"
        hx-swap="outerHTML">
  <i class="fa-regular fa-star"></i>
</button>

templates/snippets/task_list_table_row.html
{% load journal_filters %}

<tr {% if not task.is_acquainted %}class="table-success"{% endif %}>
  <td class="text-center">
    {% include "snippets/task_list_item_favorite_button.html" with task=task %}
  </td>
  <td class="text-center">
    {% if task.is_private %}
      <span class="text-muted">
        <i class="fa-solid fa-lock"></i>
      </span>
    {% endif %}
  </td>
  <td colspan="2">
    <a class="table-task-title-link" href="{{ task.get_absolute_url }}">
      {{ task.title }}
    </a>
    {% if category_id == "0" %}
      {# Do not show category here if filter by category is on #}
      <br>
      <span class="text-muted">
        <i class="fa-solid fa-tag"></i> {{ task.category }}
      </span>
    {% endif %}
  </td>
  <td class="text-center">
    <span class="text-muted">
      {{ task.comments_count }}{% if task.new_comments_count %} &middot; <span class="text-success-emphasis">{{ task.new_comments_count }}</span>{% endif %}
    </span>
  </td>
  <td>
    <span class="text-muted">
      {{ task.created }}
    </span>
  </td>
  <td>
    {% if task.completed %}
      <span class="text-muted">
        {{ task.completed }}
      </span>
    {% endif %}
  </td>
</tr>