core/urls.py
from django.urls import path

from .views import dashboard

app_name = "core"

urlpatterns = [
    path("", dashboard, name="dashboard"),
]

django_project/urls.py
import notifications.urls
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", include("core.urls")),
    path("users/", include("users.urls")),
    path("journal/", include("journal.urls")),
    path("documents/", include("documents.urls")),
    path("adminpanel/", admin.site.urls),
    path(
        "accounts/", include("django.contrib.auth.urls")
    ),  # Must be "accounts/" to work properly
    # 3rd
    path(
        "inbox/notifications/", include(notifications.urls, namespace="notifications")
    ),
    path("__debug__/", include("debug_toolbar.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# Configure Admin panel titles
admin.site.site_header = "Панель управления Журнала Дежурства"
admin.site.site_title = "Панель управления Журнала Дежурства"
admin.site.index_title = "Управление Журналом Дежурства"

documents/urls.py
from django.urls import path

from .views import DocumentDetailView, DocumentListView, document_acquaint

app_name = "documents"

urlpatterns = [
    path("", DocumentListView.as_view(), name="document_list"),
    path("document/<int:pk>/", DocumentDetailView.as_view(), name="document_detail"),
    path(
        "document/acquaint/<int:pk>/", document_acquaint, name="document_acquaint"
    ),  # HTMX view
]

journal/urls.py
from django.urls import path

from .api import (
    CommentListAPI,
    TaskCategoryListAPI,
    TaskDetailAPI,
    TaskListAPI,
    TaskListStatsAPI,
    comment_create_api,
    comment_edit_api,
    task_acquaint_api,
    task_toggle_favorite_api,
)
from .views import (
    CompletedTaskListView,
    FavoriteTaskListView,
    PrivateTaskListView,
    ReportListView,
    SearchView,
    TableTaskListView,
    TableTaskListVueView,
    TaskCreateView,
    TaskDetailView,
    TaskListView,
    TaskUpdateView,
    comment_add,
    comment_archive,
    comment_delete,
    comment_edit,
    comment_edit_save,
    comment_show,
    task_acquaint,
    task_search,
    task_toggle_favorite,
)

app_name = "journal"

urlpatterns = [
    path("tasks/", TaskListView.as_view(), name="task_list"),
    path("tasks/private/", PrivateTaskListView.as_view(), name="private_task_list"),
    path("tasks/favorites/", FavoriteTaskListView.as_view(), name="favorite_task_list"),
    path(
        "tasks/completed/", CompletedTaskListView.as_view(), name="completed_task_list"
    ),
    path("tasks/table/", TableTaskListView.as_view(), name="task_list_table"),
    path(
        "tasks/table/vue/", TableTaskListVueView.as_view(), name="task_list_table_vue"
    ),
    path("task/<int:pk>/", TaskDetailView.as_view(), name="task_detail"),
    path("task/create/", TaskCreateView.as_view(), name="task_create"),
    path("task/update/<int:pk>/", TaskUpdateView.as_view(), name="task_update"),
    path("task/<int:pk>/add_comment/", comment_add, name="task_comment_add"),
    path(
        "task/<int:task_pk>/delete_comment/<int:comment_pk>/",
        comment_delete,
        name="task_comment_delete",
    ),
    path(
        "task/<int:task_pk>/archive_comment/<int:comment_pk>/",
        comment_archive,
        name="task_comment_archive",
    ),
    path("task/comment/<int:comment_pk>/edit/", comment_edit, name="task_comment_edit"),
    path("task/comment/<int:comment_pk>/show/", comment_show, name="task_comment_show"),
    path(
        "task/comment/<int:comment_pk>/edit/save/",
        comment_edit_save,
        name="task_comment_edit_save",
    ),
    path("task/<int:pk>/acquaint/", task_acquaint, name="task_acquaint"),
    path("task/<int:pk>/favorite/", task_toggle_favorite, name="task_toggle_favorite"),
    path("tasks/search/", SearchView.as_view(), name="task_search"),
    path("reports/", ReportListView.as_view(), name="report_list"),
    path("tasks/htmx/search/", task_search, name="task_search_htmx"),
    # API views
    path("tasks/api/v1/stats/", TaskListStatsAPI.as_view(), name="api_task_stats"),
    path("tasks/api/v1/task_list/", TaskListAPI.as_view(), name="api_task_list"),
    path(
        "tasks/api/v1/task/<int:pk>/", TaskDetailAPI.as_view(), name="api_task_detail"
    ),
    path(
        "tasks/api/v1/task/<int:pk>/favorite/",
        task_toggle_favorite_api,
        name="api_task_toggle_favorite",
    ),
    path(
        "tasks/api/v1/category_list/",
        TaskCategoryListAPI.as_view(),
        name="api_task_category_list",
    ),
    path(
        "tasks/api/v1/comment_list/",
        CommentListAPI.as_view(),
        name="api_task_comment_list",
    ),
    path("tasks/api/v1/comment/", comment_create_api, name="api_task_comment_create"),
    path(
        "tasks/api/v1/comment/<int:pk>/edit/",
        comment_edit_api,
        name="api_task_comment_edit",
    ),
    path(
        "tasks/api/v1/task/<int:pk>/acquaint/",
        task_acquaint_api,
        name="api_task_acquaint",
    ),
]

templates/base.html
{% load static %}

<!doctype html>
<html lang="ru">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{% block title %}{% endblock title %} &mdash; Журнал Дежурства</title>

  <link href="{% static 'bootstrap-5.3.0-alpha1-dist/css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'fontawesome/css/fontawesome.css' %}" rel="stylesheet">
  <link href="{% static 'fontawesome/css/brands.css' %}" rel="stylesheet">
  <link href="{% static 'fontawesome/css/solid.css' %}" rel="stylesheet">
  <link href="{% static 'css/base.css' %}" rel="stylesheet">
  <script async src="https://stats.hazadus.ru/script.js" data-website-id="e3fb45c8-5b3c-47aa-8498-dcfa41cae484"></script>
</head>

<body>
  {% block body %}
  {% endblock body %}

  <script src="{% static 'bootstrap-5.3.0-alpha1-dist/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'js/htmx-1.8.4.min.js' %}"></script>
  <script>
    // Network stuff
    let webSocket;

    function webSocketConnect() {
      // Establish WebSocket connection, and reconnect when socket is closed.
      const url = 'ws://' + window.location.host + '/ws/notifications/';
      webSocket = new WebSocket(url);

      webSocket.onopen = function() {
        console.log('Base: WebSocket opened.');
      };

      webSocket.onmessage = function(event) {
        const notification = JSON.parse(event.data);
        console.log('Base - WS message - verb: ' + notification.verb_code + ' from ' + notification.actor.username);
        // Update badges upon receiving any notification
        // "task_add", "task_completed", "comment_add", "acquainted"
        switch (notification.verb_code) {
          case "task_add":
          case "task_completed":
          case "comment_add":
          case "acquainted":
          case "favorites_add":
            updateNewTaskCountBadges();
        }
      };

      webSocket.onclose = function(err) {
        console.log('Base: Socket is closed unexpectedly. Reconnect will be attempted in 1 second. Error:', err.message);
        setTimeout(function() {
          webSocketConnect();
        }, 1000);
      };

      webSocket.onerror = function(err) {
        console.error('Base: Socket encountered error: ', err.message, '. Closing socket.');
        webSocket.close();
      };
    }

    function updateNewTaskCountBadges() {
      // Fetches count of "new" tasks for logged in user from DRF API and updates the badges
      let url = '{% url "journal:api_task_stats" %}';
      let options = {
        method: 'GET',
        headers: {'X-CSRFToken': '{{ csrf_token }}'},
        mode: 'same-origin',
      }

      fetch(url, options).then(response => response.json()).then(stats => {
        badgeTotalNewTaskCount1.innerHTML = stats.total_new_tasks;
        badgeTotalNewTaskCount1.style.visibility = stats.total_new_tasks === 0 ? 'hidden' : 'visible';
        badgeTotalNewTaskCount2.innerHTML = stats.total_new_tasks;
        badgeTotalNewTaskCount2.style.visibility = stats.total_new_tasks === 0 ? 'hidden' : 'visible';

        badgeActiveNewTaskCount.innerHTML = stats.active_new_tasks;
        badgeActiveNewTaskCount.style.visibility = stats.active_new_tasks === 0 ? 'hidden' : 'visible';

        badgeFavoriteNewTaskCount.innerHTML = stats.favorite_new_tasks;
        badgeFavoriteNewTaskCount.style.visibility = stats.favorite_new_tasks === 0 ? 'hidden' : 'visible';

        badgeCompletedNewTaskCount.innerHTML = stats.completed_new_tasks;
        badgeCompletedNewTaskCount.style.visibility = stats.completed_new_tasks === 0 ? 'hidden' : 'visible';
      });
    }

    // Badges stuff
    let badgeTotalNewTaskCount1 = document.getElementById('badge-total-new-task-count-1');
    let badgeTotalNewTaskCount2 = document.getElementById('badge-total-new-task-count-2');
    let badgeActiveNewTaskCount = document.getElementById('badge-active-new-task-count');
    let badgeFavoriteNewTaskCount = document.getElementById('badge-favorite-new-task-count');
    let badgeCompletedNewTaskCount = document.getElementById('badge-completed-new-task-count');

    document.addEventListener('DOMContentLoaded', () => {
      // Connect to WebSocket
      webSocketConnect();

      // Init HTMX
      document.body.addEventListener('htmx:configRequest', (event) => {
        event.detail.headers['X-CSRFToken'] = '{{ csrf_token }}';
      });

      // Initial update of badges
      updateNewTaskCountBadges();

      // Init Bootstrap tooltips
      const tooltipTriggerList = document.querySelectorAll('[data-bs-toggle="tooltip"]');
      const tooltipList = [...tooltipTriggerList].map(tooltipTriggerEl => new bootstrap.Tooltip(tooltipTriggerEl));

      {% block domready %}
      {% endblock domready %}
    });
  </script>
  {% block footer_scripts %}
  {% endblock footer_scripts %}
</body>

</html>

templates/base_dashboard.html
{% extends "base.html" %}

{% load static %}

{% block body %}
  <header class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0 shadow">
    <a class="navbar-brand col-md-3 col-lg-2 me-0 px-3 fs-6 text-center" href="{% url 'core:dashboard' %}">
      <i class="fa-solid fa-book-bookmark" style="color: var(--bs-primary-border-subtle);"></i>
      Журнал Дежурства
    </a>
    <button class="navbar-toggler position-absolute d-md-none collapsed" type="button" data-bs-toggle="collapse"
      data-bs-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <input class="form-control form-control-dark w-100 rounded-0 border-0"
           type="search" name="search" id="search"
           placeholder="Начните печатать для поиска по задачам..."
           hx-post="{% url 'journal:task_search_htmx' %}"
           hx-trigger="keyup changed delay:500ms, search"
           hx-target="#dashboard-page-content"
           aria-label="Search">
  </header>

  <div class="container-fluid" style="height: calc(100% - 48px);">
    <div class="row">
      <nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
        <div class="position-sticky pt-3 sidebar-sticky">
          <!-- User profile menu -->
          <div class="dropdown ms-3">
            <a href="#" class="d-flex align-items-center text-dark text-decoration-none dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
              <div class="me-2">
                {% include "snippets/user_avatar.html" with user=user size=32 %}
              </div>
              <strong>{{ user.short_name }}</strong>
            </a>
            <ul class="dropdown-menu dropdown-menu-dark text-small shadow">
              <li>
                <a class="dropdown-item" href="{% url 'journal:task_create' %}">
                  <i class="fa-solid fa-file-circle-plus"></i> Создать задачу
                </a>
              </li>
              <li><hr class="dropdown-divider"></li>
              <li>
                <a class="dropdown-item" href="{% url 'logout' %}">
                  <i class="fa-solid fa-arrow-right-from-bracket"></i> Выйти из аккаунта
                </a>
              </li>
            </ul>
          </div>
          <hr>

          <ul class="nav flex-column">
            <li class="nav-item {% if "/" == request.path %}nav-item-active{% endif %}">
              <a class="nav-link {% if "/" == request.path %}active{% endif %}" aria-current="page" href="{% url 'core:dashboard' %}">
                <i class="fa-solid fa-book"></i> Журнал
              </a>
            </li>
            <li class="nav-item {% if "/journal/tasks/" == request.path %}nav-item-active{% endif %}">
              <a class="nav-link {% if "/journal/tasks/" == request.path %}active{% endif %}" href="{% url 'journal:task_list' %}">
                <i class="fa-solid fa-list-check"></i> Задачи
                <span id="badge-active-new-task-count" class="badge text-bg-success" style="visibility: hidden;"></span>
              </a>
            </li>

            <!-- Subitems -->
            <li class="nav-item {% if "/journal/tasks/table/" == request.path %}nav-item-active{% endif %}" style="margin-left: 20px;">
              <a class="nav-link {% if "/journal/tasks/table/" == request.path %}active{% endif %}" href="{% url 'journal:task_list_table' %}">
                <i class="fa-solid fa-table"></i> Таблица
                <span id="badge-total-new-task-count-1" class="badge text-bg-success" style="visibility: hidden;"></span>
              </a>
            </li>
            <li class="nav-item {% if "/tasks/table/vue/" in request.path %}nav-item-active{% endif %}" style="margin-left: 20px;">
              <a class="nav-link {% if "/tasks/table/vue/" in request.path %}active{% endif %}" href="{% url 'journal:task_list_table_vue' %}">
                <i class="fa-solid fa-columns"></i> Колонки
                <span id="badge-total-new-task-count-2" class="badge text-bg-success" style="visibility: hidden;"></span>
              </a>
            </li>
            <li class="nav-item {% if "/tasks/private/" in request.path %}nav-item-active{% endif %}" style="margin-left: 20px;">
              <a class="nav-link {% if "/tasks/private/" in request.path %}active{% endif %}" href="{% url 'journal:private_task_list' %}">
                <i class="fa-solid fa-lock"></i> Личные
              </a>
            </li>
            <li class="nav-item {% if "/tasks/favorites/" in request.path %}nav-item-active{% endif %}" style="margin-left: 20px;">
              <a class="nav-link {% if "/tasks/favorites/" in request.path %}active{% endif %}" href="{% url 'journal:favorite_task_list' %}">
                <i class="fa-regular fa-star"></i> Избранные
                <span id="badge-favorite-new-task-count" class="badge text-bg-success" style="visibility: hidden;"></span>
              </a>
            </li>
            <li class="nav-item {% if "/tasks/completed/" in request.path %}nav-item-active{% endif %}" style="margin-left: 20px;">
              <a class="nav-link {% if "/tasks/completed/" in request.path %}active{% endif %}" href="{% url 'journal:completed_task_list' %}">
                <i class="fa-solid fa-check-double"></i> Завершенные
                <span id="badge-completed-new-task-count" class="badge text-bg-success" style="visibility: hidden;"></span>
              </a>
            </li>

            <li class="nav-item {% if "/documents/" in request.path %}nav-item-active{% endif %}">
              <a class="nav-link {% if "/documents/" in request.path %}active{% endif %}" href="{% url 'documents:document_list' %}">
                <i class="fa-solid fa-file-invoice"></i> Документы
                {% with count=green_active_documents.count %}
                  {% if count %}
                    <span class="badge text-bg-success">{{ count }}</span>
                  {% endif %}
                {% endwith %}
              </a>
            </li>
            <li class="nav-item {% if "/tasks/search/" in request.path %}nav-item-active{% endif %}">
              <a class="nav-link {% if "/tasks/search/" in request.path %}active{% endif %}" href="{% url 'journal:task_search' %}">
                <i class="fa-solid fa-magnifying-glass"></i> Поиск
              </a>
            </li>
            <li class="nav-item {% if "/journal/reports/" in request.path %}nav-item-active{% endif %}">
              <a class="nav-link {% if "/journal/reports/" in request.path %}active{% endif %}" href="{% url 'journal:report_list' %}">
                <i class="fa-solid fa-chart-line"></i> Отчёты
              </a>
            </li>
          </ul>

          {% if user.is_superuser %}
          <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted text-uppercase">
            <span>Администратор</span>
            <a class="link-secondary" href="#" aria-label="Add a new report">
              <i class="fa-solid fa-circle-plus"></i>
            </a>
          </h6>
          <ul class="nav flex-column mb-auto">
            <li class="nav-item">
              <a class="nav-link" href="/adminpanel/">
                <i class="fa-solid fa-screwdriver-wrench"></i> Панель управления
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="https://darussianbearz.sentry.io/issues/?project=4504825355698176&referrer=sidebar">
                <i class="fa-solid fa-binoculars"></i> Sentry
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="https://rollbar.com/hazadus7/all/items/?sort=%5Bobject%20Object%5D&status=active&date_from=&date_to=&environments=development&activated_to=&framework=&levels=10&levels=20&levels=30&levels=40&levels=50&activated_from=&offset=0&timezone=Europe%2FMoscow&assigned_user=&date_filtering=seen&projects=612049&query=&enc_query=">
                <i class="fa-solid fa-bug"></i> Rollbar
              </a>
            </li>
          </ul>
          {% endif %}

        </div>
      </nav>

      <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
        <!-- Dashboard page content -->
        <div id="dashboard-page-content">
          <!-- Dashboard page header -->
          <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-baseline pt-3 pb-2 mb-3 border-bottom">
            {% block dashboard_page_header %}
            {% endblock dashboard_page_header %}
          </div>

          <!-- CONTENT -->
          {% block content %}
          {% endblock content %}
          <!-- END CONTENT -->
        </div>
      </main>
    </div>
  </div>
{% endblock body %}

templates/base_dashboard_task_list.html
{% extends "base_dashboard.html" %}

{% block dashboard_page_header %}
  <h1 class="h2">{% block title %}{% endblock title %}</h1>
  <div class="btn-toolbar mb-2 mb-md-0">
  <!--
    <div class="btn-group me-2">
      <button type="button" class="btn btn-sm btn-outline-secondary"><i class="fa-solid fa-download"></i> <i class="fa-solid fa-file-csv"></i></button>
      <button type="button" class="btn btn-sm btn-outline-secondary"><i class="fa-solid fa-download"></i> <i class="fa-solid fa-file-pdf"></i></button>
    </div>
    -->
    <!-- Sort dropdown -->
    <div class="dropdown dropdown-task-list-order">
      <button type="button" class="btn btn-sm btn-outline-secondary dropdown-toggle task-list-dropdown me-2"
              data-bs-toggle="dropdown" aria-expanded="false">
        <i class="fa-solid fa-sort"></i> Порядок:
        {% if order_by == "latest_comment" %}
          по последним комментариям <i class="fa-solid fa-arrow-down-9-1"></i>
        {% elif order_by == "created"%}
          по времени создания <i class="fa-solid fa-arrow-down-9-1"></i>
        {% elif order_by == "completed"%}
          по времени завершения <i class="fa-solid fa-arrow-down-9-1"></i>
        {% endif %}
      </button>
      <ul class="dropdown-menu text-small shadow">
        <li>
          <a class="dropdown-item {% if order_by == "created" %}active{% endif %}"
             href="{% if order_by == "created" %}#{% else %}{{ request.path }}?order_by=created{% endif %}">
            <i class="fa-solid fa-arrow-down-9-1"></i> По времени создания задачи
          </a>
        </li>
        <li>
          <a class="dropdown-item {% if order_by == "latest_comment" %}active{% endif %}"
             href="{% if order_by == "latest_comment" %}#{% else %}{{ request.path }}?order_by=latest_comment{% endif %}">
            <i class="fa-solid fa-arrow-down-9-1"></i> По последним комментариям
          </a>
        </li>
        <li>
          <a class="dropdown-item {% if order_by == "completed" %}active{% endif %}"
             href="{% if order_by == "completed" %}#{% else %}{{ request.path }}?order_by=completed{% endif %}">
            <i class="fa-solid fa-arrow-down-9-1"></i> По времени завершения
          </a>
        </li>
        <li>
          <a class="dropdown-item disabled" href="#">
            <i class="fa-solid fa-arrow-down-9-1"></i> По сроку выполнения
          </a>
        </li>
      </ul>
    </div>
    <!-- Filter dropdown -->
    <div class="dropdown dropdown-task-list-filter">
      <button type="button" class="btn btn-sm btn-outline-secondary dropdown-toggle task-list-dropdown me-2"
              data-bs-toggle="dropdown" aria-expanded="false">
        <i class="fa-solid fa-filter"></i> Фильтр:
        {% if get_hide_private %}скрыть личные{% else %}нет{% endif %}
      </button>
      <ul class="dropdown-menu text-small shadow">
        <li>
          <a class="dropdown-item {% if get_hide_private %}active{% endif %}" href="{{ request.path }}{% if get_hide_private %}?hide_private=false{% else %}?hide_private=true{% endif %}">
            <i class="fa-solid fa-lock"></i> Скрыть личные
          </a>
        </li>
        <li><hr class="dropdown-divider"></li>
        <li><a class="dropdown-item" href="{{ request.path }}?hide_private=false"><i class="fa-solid fa-filter-circle-xmark"></i> Очистить фильтр</a></li>
      </ul>
    </div>

    <a class="btn btn-sm btn-success" href="{% url 'journal:task_create' %}">
      <i class="fa-solid fa-file-circle-plus"></i> Добавить задачу
    </a>
  </div>
{% endblock dashboard_page_header %}

templates/dashboard.html
{% extends "base_dashboard.html" %}

{% block title %}Журнал событий{% endblock title %}

{% block dashboard_page_header %}
  <h1 class="h2">
    Журнал событий
  </h1>
  <div class="btn-toolbar mb-2 mb-md-0">
    <a class="btn btn-sm btn-success" href="{% url 'journal:task_create' %}">
      <i class="fa-solid fa-file-circle-plus"></i> Добавить задачу
    </a>
  </div>
{% endblock dashboard_page_header %}

{% block content %}
  <!-- Timeline -->
  <div class="timeline">
    <!-- Left vertical line -->
    <div class="timeline__line"></div>

    <!-- The timeline items timeline -->
    <div class="timeline__items">
      {% include "snippets/dashboard_timeline_items.html" with notifications=notifications%}
    </div>
  </div>

{% endblock content %}

templates/document_detail.html
{% extends "base_dashboard.html" %}

{% block title %}
  {{ document.title }}
{% endblock title %}

{% block dashboard_page_header %}
  <h1 class="h2">
    {% if document.is_completed %}
      <i class="fa-solid fa-file-circle-check"></i>
    {% endif %}
    {{ document.title }}
  </h1>
{% endblock dashboard_page_header %}

{% block content %}
  {% include "snippets/document_detail_item.html" with document=document %}

  {% if user.is_superuser %}
    <h3 class="mt-3 mb-3">
      Ознакомление пользователей
    </h3>
    <!-- Timeline -->
    <div class="timeline ms-3">
      <!-- Left vertical line -->
      <div class="timeline__line"></div>

      <!-- The timeline items timeline -->
      <div class="timeline__items">
        {% include "snippets/dashboard_timeline_items.html" with notifications=document_notifications %}
      </div>
    </div>
  {% endif %}
{% endblock content %}

templates/document_list.html
{% extends "base_dashboard.html" %}

{% block title %}Актуальные документы и поручения{% endblock title %}

{% block dashboard_page_header %}
  <h1 class="h2">
    Актуальные документы и поручения
  </h1>
{% endblock dashboard_page_header %}

{% block content %}
  {% if document_list %}
    <div class="row">
      <div class="col-12 col-md-3">
        <nav class="nav flex-column">
          <li class="nav-item {% if not category_id %}nav-item-active{% endif %}">
            <a class="nav-link" href="{% url 'documents:document_list' %}">
              Все документы ({{ total_count }})
            </a>
          </li>
          {% for category in categories %}
            {% if category.document_qty %}
              <li class="nav-item {% if category_id == category.id %}nav-item-active{% endif %}">
                <a class="nav-link" href="{% url 'documents:document_list' %}?category_id={{ category.id }}">
                  {{ category.title }} ({{ category.document_qty }})
                </a>
              </li>
            {% endif %}
          {% endfor %}
        </nav>
      </div>
      <div class="col-12 col-md-9">
        {# List `green` documents on top of the list #}
        {% for document in document_list %}
          {% if not user in document.users_acquainted.all %}
            {% include "snippets/document_list_item.html" with document=document %}
          {% endif %}
        {% endfor %}
        {# List other documents #}
        {% for document in document_list %}
          {% if user in document.users_acquainted.all %}
            {% include "snippets/document_list_item.html" with document=document %}
          {% endif %}
        {% endfor %}
      </div>
    </div>
  {% else %}
    <div class="alert alert-info">
      <i class="fa-solid fa-circle-info"></i> Нет документов и поручений, удовлетворяющих заданным параметрам.
    </div>
  {% endif %}
{% endblock content %}

templates/search.html
{% extends "base_dashboard.html" %}

{% block title %}Поиск по задачам{% endblock title %}

{% block dashboard_page_header %}
  <h1 class="h2">
    Поиск по задачам
  </h1>
{% endblock dashboard_page_header %}

{% block content %}
  <div class="alert alert-info">
    <i class="fa-solid fa-circle-info"></i> Для поиска задач по заголовку, тексту, или тексту в комментариях,
    начните печатать искомый текст в поле вверху страницы. Результаты будут выводиться автоматически.
  </div>
{% endblock content %}

<script>
{% block domready %}
  // Auto-focus on Search field
  searchField = document.getElementById("search");
  searchField.focus();
{% endblock domready %}
</script>

templates/task_detail.html
{% extends "base_dashboard.html" %}

{% block title %}
  {{ task.title }}
{% endblock title %}

{% block dashboard_page_header %}
  <h1 class="h2">
    {% if task.is_completed %}
      <i class="fa-solid fa-file-circle-check"></i>
    {% endif %}
    {{ task.title }}
  </h1>
  <div class="btn-toolbar mb-2 mb-md-0 flex-shrink-0">
    <a class="btn btn-sm btn-success" href="{% url 'journal:task_create' %}">
      <i class="fa-solid fa-file-circle-plus"></i> Добавить задачу
    </a>
  </div>
{% endblock dashboard_page_header %}

{% block content %}
  {% include "snippets/task_full_block.html" with task=task %}
{% endblock content %}

<script>
{% block domready %}
  // Declare variables for DOM elements, they will be assigned in "task_comments_block.html" <script> section.
  // This separation is needed for HTMX to work properly on partial page reloads, when these DOM elements are changed.
  let completedCheckBox;
  let commentTextarea;
  let submitButton;
{% endblock %}
</script>